### PR TITLE
fix high pins

### PR DESCRIPTION
**Pull request by ladyada**
this chip doesnt auto-increment the i2c ptr?

### CODE REVIEW

**Comment by epinzur** [comment]
is this to fix reading digital out on pins 8-15?

**Comment by ladyada** [comment]
it should! wanna try?

**Comment by epinzur** [comment]
it works! 

Thanks for putting this PR up 2 days before I started debugging this.  If I didn't find the PR I would have been quite frustrated.

**Comment by ladyada** [comment]
whats odd is...it definitely used to work? so what changed i dont know :(

**Pull request merged**
